(source gnu)
(source melpa)

(depends-on "evil")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "exec-path-from-shell")
(depends-on "smartparens")
(depends-on "use-package")
(depends-on "init-loader")
(depends-on "ace-jump-mode")
(depends-on "helm")
(depends-on "web-mode")
(depends-on "ein")
(depends-on "yatex")
(depends-on "mozc")
(depends-on "elscreen")
(depends-on "elscreen-separate-buffer-list")
