(require 'package)
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/") t)

(defun check-package()
  (package-refresh-contents)
  (package-install 'use-package)
  (package-install 'init-loader)
  (package-install 'helm)
  (package-install 'exec-path-from-shell)
  (package-install 'expand-region)
  (package-install 'smartrep)
  (package-install 'elscreen)
  (package-install 'ace-isearch)
  (package-install 'quickrun)
  (package-install 'popwin)
  (package-install 'rainbow-delimiters)
  (package-install 'smartparens)
  (package-install 'ein)
  (package-install 'eval-in-repl)
  (package-install 'flycheck)
  (package-install 'flycheck-pos-tip)
  (package-install 'magit)
  (package-install 'mozc)
  (package-install 'web-mode)
  (package-install 'codic)
  (package-install 'geiser)
  (package-install 'auto-complete)
  (package-install 'ac-geiser)
  (package-install 'yasnippet)
  (package-install 'helm-c-yasnippet)
  (package-install 'rotate)
  (package-install 'golden-ratio)
  (package-install 'evil)
  (package-install 'indent-guide)
  (package-install 'jedi)
  (package-install 'linum-relative)
  (package-install 'markdown-mode)
  (package-install 'neotree)
  )

;;; (check-package)
(exec-path-from-shell-initialize)

(require 'use-package)
(require 'init-loader)
(init-loader-load "~/.emacs.d/elisp")
(init-loader-load "~/.emacs.d/core")
(init-loader-load "~/.emacs.d/appearance")
(init-loader-load "~/.emacs.d/extensions")

;;; language 上書きされガチなので一番最後に設定する
(set-language-environment "Japanese")
(prefer-coding-system 'utf-8)
(setq default-process-coding-system 'utf-8)
(setq default-input-method "japanese-mozc")
(setq mozc-candidate-style 'overlay)
