(require 'package)
(package-initialize)

(defun check-package()
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-refresh-contents)
  (package-install 'use-package)
  (package-install 'init-loader)
  (package-install 'helm)
  (package-install 'exec-path-from-shell)
  (package-install 'expand-region)
  (package-install 'smartrep)
  (package-install 'elscreen)
  (package-install 'ace-isearch)
  (package-install 'quickrun)
  (package-install 'popwin)
  (package-install 'rainbow-delimiters)
  (package-install 'smartparens)
  )

;;; (check-package)
(exec-path-from-shell-initialize)

(require 'use-package)
(require 'init-loader)
(custom-set-variables
 '(init-loader-show-log-after-init 'error-only))
(init-loader-load "~/.emacs.d/core")
(init-loader-load "~/.emacs.d/appearance")
(init-loader-load "~/.emacs.d/extensions")
