(require 'package)
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/") t)
(package-refresh-contents)

;;; install packages
(package-install 'use-package)
(package-install 'init-loader)
(package-install 'helm)
(package-install 'exec-path-from-shell)
(package-install 'smartrep)
(package-install 'elscreen)
(package-install 'quickrun)
(package-install 'popwin)
(package-install 'rainbow-delimiters)
(package-install 'smartparens)
(package-install 'ein)
(package-install 'flycheck)
(package-install 'flycheck-pos-tip)
(package-install 'magit)
(package-install 'mozc)
(package-install 'web-mode)
(package-install 'geiser)
(package-install 'auto-complete)
(package-install 'ac-geiser)
(package-install 'yasnippet)
(package-install 'helm-c-yasnippet)
(package-install 'rotate)
(package-install 'evil)
(package-install 'indent-guide)
(package-install 'jedi)
(package-install 'linum-relative)
(package-install 'markdown-mode)
(package-install 'neotree)
(package-install 'evil-smartparens)

;;; upgrade packages
(package-list-packages)
(package-menu-mark-upgrades)
(package-menu-execute)

;;; install jedi server
(jedi:install-server)
