(add-hook 'python-mode-hook '(lambda ()
                               (jedi:setup)
                               (py-autopep8-enable-on-save)))
(add-hook 'ein:notebook-mode-hook 'jedi:setup)
(setq jedi:complete-on-dot t)
