(require 'popwin)
(popwin-mode t)
(push '("*quickrun*" :height 20 :noselect t) popwin:special-display-config)
(push '("*Backtrace*" :height 20) popwin:special-display-config)
(push '("*Codic Result*" :height 20) popwin:special-display-config)
(push '("*Geiser dbg*" :height 20) popwin:special-display-config)
(push '("*Warnings*" :height 20) popwin:special-display-config)
(push '("*magit:" :regexp t :height 20) popwin:special-display-config)
