(global-unset-key (kbd "M-w"))
(smartrep-define-key global-map "M-w"
  '(("d" . 'delete-window)
    ("D" . 'delete-other-windows)
    ("=" . 'evil-window-increase-height)
    ("-" . 'evil-window-decrease-height)
    ("<" . 'evil-window-decrease-width)
    (">" . 'evil-window-increase-width)
    ("h" . 'evil-window-left)
    ("j" . 'evil-window-down)
    ("k" . 'evil-window-up)
    ("l" . 'evil-window-right)
    ("v" . 'evil-window-vsplit)
    ("h" . 'evil-window-split)
    ("+" . 'my/text-scale-increase)
    ("_" . 'my/text-scale-decrease)
    ("r" . 'rotate-layout)
    ("R" . 'rotate-window)
    )
  )

(golden-ratio-mode t)
