(defun forward-word+1()
  (interactive)
  (forward-word)
  (forward-char))

(defun back)
(bind-keys 
 ("M-z" . undo)
 ("C-u" . set-mark-command)
 ("C-h" . delete-backward-char)
 ("C-'" . hs-toggle-hiding)
 ("C-x C-c" . helm-M-x)
 ("M-p" . scroll-down)
 ("M-n" . scroll-up)
 ("M-f" . forward-word+1)
 ("M-b" . backward-word))
